### ISSUE TITLE
use rvfc to resize canvas instead of .on('resize') and videoHeight

### ISSUE THREAD

**Issue by po5** [ThaUnknown/jassub#17]
This fixes typesetting on anamorphic videos.

**Comment by ThaUnknown** [comment]
you lazy motherfucker

HTMLVideoElement.prototype.videoHeight reports the renderer video resolution, not the video's true resolution, this causes some subtitles to render incorrectly, RVFC reports the true resolution so it should be used for that instead

the issue is that supporting this requires quite a significant rewrite, as the canvas's ctx size and the canvas's element size is currently tightly linked, and this would need to resize the canvas ctx each frame, during rendering, likely also fixing #16

**Comment by ThaUnknown** [comment]
d431f2aa0056731f75c85bf6775c94eea3d31c16
