### ISSUE TITLE
[Feature Request] Having a parameter to set the WASM URL

### ISSUE THREAD

**Issue by ThibaultNocchi** [ThaUnknown/jassub#20]
Hello,

As specified in #6, Vite bundles files with a hash. As `jassub` tries to load the WASM file from a static filename, loading it fails.

Solutions are either using the static copy plugin or disabling hashing by Vite.

I'm wondering if it'd be possible to have a parameter, such as the `workerUrl` one, to pass the WASM URL?

I've looked into the code, but I don't have the skills to see if it can be implemented as I don't have much experience with workers.

I don't mind if it's not implemented, just asking if it could be possible.

Thanks a lot!

**Comment by ThibaultNocchi** [comment]
Ok, no problem then. Thank you!

**Comment by ThaUnknown** [comment]
because you need to modify a lot in the emscripten build steps to keep the same "entry level" aka keep browser requirements low and be able to modify the path, and hate to break it to you but even with a custom path even if you magically change the WASM file during your development which is stupidly unlikely, it won't actually change the WASM, and EVEN IF you provided a custom path you'd still need to static copy the .wasm but with the hash...

WASM isn't really a problem in not counting it towards the bundle size stats and it really shouldnt be

**Comment by ferferga** [comment]
@ThaUnknown I wasn't talking about development, ofc hashing on development is useless.

My point was more towards production, where a version bump of your dependency where the WASM is also modified doesn't propagate in a deterministic way to clients, which might have cached versions.

**Comment by ThaUnknown** [comment]
yeah that's fair, honestly I don't know what's the best way to solve this issue, I've never really seen or used any libraries which used workers so I don't really know what's the "go-to" for this kind of thing

**Comment by ThaUnknown** [comment]
this was added in latest
