### ISSUE TITLE
Importing the WASM file via vite breaks in production

### ISSUE THREAD

**Issue by Arnagos** [ThaUnknown/jassub#6]
First: Thanks for this great project!

Importing the WASM worker file via `import 'jassub/dist/jassub-worker.wasm?url'` does not work in production because Vite adds a hash to the file name.

My workaround is using the 'vite-plugin-static-copy' to copy the file instead.

Do you know a way to get vite to not add the hash (without manually copying the file to the assets)? Otherwise I'd change the documentation.

And a small side question: Should the `default.woff2` be copied as well?

**Comment by ThaUnknown** [comment]
thanks, I'm surprised anyone actually uses this, since its effectively just a clone of JSSO, but faster and smaller

in your vite config
```js
export default defineConfig({
  // ...
  build: {
    rollupOptions: {
      output: {
        assetFileNames: '[name].[ext]'
      }
    }
  }
})
```
will prevent rollup [vite] from using random hashes

default.woff2 depends on your use cases and configs, if you dont add any available fonts and dont change the fallback font, then you probably should [unless you use `useLocalFonts` but that feature is not supported in 95% of browsers, and I made it mainly for electron applications]. By default liberation sans is the default fallback font
![image](https://user-images.githubusercontent.com/6506529/181744336-b2edca06-2af3-471f-959c-8ebcab4ffa9c.png)

but you can change it to anything else u want and you wont need to include the font
