### ISSUE TITLE
Firefox: Subtitle resolution does not adapt to video

### ISSUE THREAD

**Issue by Arnagos** [ThaUnknown/jassub#9]
The subtitle resolution does not adapt to the video resolution leading to extremely low-quality subtitles.
So far only been observed in Firefox.

Example:
![image](https://user-images.githubusercontent.com/21961872/187540141-e70c7b38-598a-4bac-a358-cf724a1745fd.png)

**Comment by ThaUnknown** [comment]
I assume this is firefox being shit and not to spec, and not firing the `resize` event on the video, I'll patch this

**Comment by Arnagos** [comment]
The [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) is not ready yet. Disabling the feature in the about:config fixes this issue.

**Comment by GizmoTjaz** [comment]
Support for [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) was added in Firefox 105, yet the issue still persists with the following error:

![2022-10-23 16-00-13](https://user-images.githubusercontent.com/25076630/197396699-c3cb28e9-0612-4150-8f12-e32548c4d768.png)

**Comment by ThaUnknown** [comment]
> Support for [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) was added in Firefox 105, yet the issue still persists with the following error:
> 
> ![2022-10-23 16-00-13](https://user-images.githubusercontent.com/25076630/197396699-c3cb28e9-0612-4150-8f12-e32548c4d768.png)

then they didn't do it right

**Comment by ThaUnknown** [comment]
OffscreenCanvas is a brand new feature, just like local font access, this shit will happen, which is why I left settings for the developers to toggle them themselves if they so see fit. Supporting experimental API's is always risky but rewarding, if you find a fix for this feel free to PR it but to my knowledge I did everything according to spec, so ff is more to blame than anything since this suggests u cant resize offscreen canvases, which is bs
